### ISSUE TITLE
Owner update URC30 token fee while the other transferring might cause unwanted charged fee.

### ISSUE THREAD

**Issue by elonkusk** [uniworld-io/unichain-core#17]
PROBLEMS:
Owner update URC30 token fee while the other transferring might cause an unwanted charged fee

SUGGESTED SOLUTIONS:
- pending update URC30 token params until maintaining block
- show status pending params update on API
@henry-ngv please leave a comment.

**Comment by henry-ngv** [comment]
The maintaining update should be suitable for network parameters such as the reward per block, transaction fee per byte ... 
If there are 100k of token need to be updated, the process will take time and may cause some other problems.
My proposal is that when the following (or more) attributes are updated, We mark that token is updated (by change update_time attribute for example):
- Update token fee
- Update token extra fee
- Update token owner
- Update token rate (rate to UNW)
If token is updated, It will not be used for at least 3 minutes so that every users will aware of token update.
My pseudo code:
```java
transferToken (token_name, from, to, amount) {
 token = getTokenInfo(token_name);
 if (now() - token.update_time < 3*60) {
   return "Error: Token is update recently. Please wait for 3 minutes before used";
 }
}
```

**Comment by elonkusk** [comment]
@henry-ngv  
- updating critical token params might affect TokenExchangeContract also, not only TokenTransferContract
- should we check when token burned/mint ?
- this feature will be supported on block version >= 3

**Comment by elonkusk** [comment]
@realelonmusk102 please note that:

- this new feature applies on block version >= 3 only
- with block version 2: don't check
- this feature should work with token created in block version <= 2 when network upgrade to version 3
